name = "ObjectPools"
uuid = "b712c73f-ba9b-5390-8459-c3417ce2dceb"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.1.1"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
